apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app
spec:
  replicas: 3  # <== 3 nodes inside the cluster
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app
          image: sayyedsameer0208/kubernetes-project-product-app:latest  # 👈 Push your image first
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/kubernetes_project_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: sameer
