package com.effigopracticeproject.learning_portal.mapper;

import com.effigopracticeproject.learning_portal.dto.CourseRequestDto;
import com.effigopracticeproject.learning_portal.entity.Course;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper(componentModel = "spring")
public interface CourseRequestDtoMapper {

    @Mapping(target = "courseId", ignore = true) // Ignore the ID as it will be generated by DB
    @Mapping(target = "registeredCourses", ignore = true) // If you don't want to set registered courses here
    Course courseRequestDtoToEntity(CourseRequestDto courseRequestDto);
}
