version: '3.8'

services:
  data-receiver:
    image: data-receiver:latest
    build:
      context: .  # Adjust path to your app2
      dockerfile: Dockerfile
    container_name: data-receiver
    ports:
      - "8081:8081"  # Expose port 8088 for app2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/receiver_data_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sameer
    depends_on:
      - db
    networks:
      - spring-network  # Use an external shared network

  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: receiver_data_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sameer
    ports:
      - "5433:5432"  # Expose PostgreSQL port
    networks:
      - spring-network
    volumes:
      - db-data:/var/lib/postgresql/data  # Persist data between container restarts

networks:
  spring-network:
    external: true  # Use external network

volumes:
  db-data:
    driver: local