#version: '2'
#
#services:
#  app:
#    image: learning-portal:v1
#    container_name: app
#    depends_on:
#      - db
#    ports:
#      - "9000:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/learning_portal
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=sameer
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    image: postgres:17
#    container_name: db_container
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=sameer
#      - POSTGRES_DB=learning_portal


version: "3.8"

services:
  backend:
    build: .  # Change from './learning-portal' to '.' (current directory)
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/learning_portal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sameer

  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: learning_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sameer
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
