version: '3'
services:
  postgres:
    image: postgres:17
    container_name: postgresdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
        #volumes:
      #- postgres_data:/var/lib/postgresql/data
