spring:
  application:
    name: transaction-producer
  datasource:
    dbcp2:
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://training1.effigo.in:5432/training_2
    username: upeg
    password: sillicon
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    main: transaction-topic
    fallback: transaction-fallback

app:
  kafka:
    topic:
      master-item: master-item-topic
      fallback: fallback-topic

logging:
  level:
    org.springframework: debug
    com.effigoproject.transactionproducer: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG